### ISSUE TITLE
configure.ac requires c++ standard edit to build on Debian Unstable

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-system-monitor#59] opened 2015-10-07 04:29 UTC
Beginning with building 1.11.0 on October 6, building mate-system-monitor on Debian Unstable (with gtk3 if that makes any difference) errors out with 
"note: C++11 ‘noexcept’ only available with -std=c++11 or -std=gnu++11"
followed by multiple errors.

Replacing
CXXFLAGS="-Wall -std=c++98 $CXXFLAGS"
with
CXXFLAGS="-Wall -std=c++11 $CXXFLAGS"
allows the build to finish and I didn't get any runtime issues

**Comment by sunweaver** [comment] 2015-10-07 08:09
Confirmed here. Will fix this in Debian... Please fix it upstream, too.

**Comment by sunweaver** [comment] 2015-10-07 08:21
http://anonscm.debian.org/cgit/pkg-mate/mate-system-monitor.git/diff/debian/patches/1002_stdc++11.patch?id=1f29cad8d66cfe722d226aeb26f3d1d41666b3df

**Comment by raveit65** [comment] 2015-10-07 08:33
@sunweaver 
Pull request?

**Comment by raveit65** [comment] 2015-10-13 22:46
confirmed, happens in fedora rawhide too.
Why can downstream mantainer not help our small team and send a PR?

**Comment by raveit65** [comment] 2015-10-13 23:08
libstdc++ needs to add to configure.ac, otherwise distcheck (or make) failed on a box without libstdc++-devel installed.
make complains about missing /usr/bin/g++

**Comment by sunweaver** [comment] 2015-10-14 03:10
Hi Wolfgang,

On  Mi 14 Okt 2015 00:46:16 CEST, Wolfgang Ulbrich wrote:

> confirmed, happens in fedora rawhide too.
> Why can downstream mantainer not help our small team and send a PR?

Because during the past few weeks I had zero time for extra tasks.  
Copy+Pasting a patch URL is one thing (you may or may not accept it  
upstream). But going through a full review process for patch  
submission is currently not not a priority as not enough time is  
reserved for that here.

light+love,
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by raveit65** [comment] 2015-10-14 10:21
Whow,
running git clone, applyinng the patch, git pull, clicking on PR button is a 5 min job.

**Comment by sunweaver** [comment] 2015-10-14 10:27
Hi Wolfgang,

On  Mi 14 Okt 2015 12:21:29 CEST, Wolfgang Ulbrich wrote:

> Whow,
> running git clone, applyinng the patch, git pull, clicking on PR  
> button is a 5 min job.

yes and... getting feedback... being asked to update the patch... etc.  
turns me into an upstream dev. This I don't have time and focus for.

Please accept that and be happy about me forwarding the patches I/we  
create (instead of keeping them in debian/patches/ only).

light+love,
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976 148

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/freebusy/m.gabriel%40das-netzwerkteam.de.xfb

**Comment by raveit65** [comment] 2015-10-14 11:29
Please accept and be happy that my my focus is fedora and not debian, and i do not have the time for it :)

**Comment by monsta** [comment] 2015-10-15 11:49
Fixed in https://github.com/mate-desktop/mate-system-monitor/commit/56594f6f10ba04aa51af976bc8339ea9ae54ea21 - now supports both c++ standards.

**Closed by monsta** 2015-10-15 11:49 UTC

**Comment by lukefromdc** [comment] 2015-10-16 03:06
Built this today, it works
