### ISSUE TITLE
Killing other user's processes crashes the program.

### ISSUE THREAD

**Issue by maandree** [mate-desktop/mate-system-monitor#75] opened 2015-12-11 22:19 UTC
```
The program 'mate-system-monitor' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 25062 error_code 8 request_code 1 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

But kudos on not spewing a bounch of crap this stderr as usual.

**Comment by raveit65** [comment] 2015-12-11 23:36
I'm so bored about reports like this.....
Distro?
packge release version?
It's not the first time that you report issues.
I will close this report if you not provide basic infos :P

**Comment by maandree** [comment] 2015-12-11 23:42
Did you even try it? Please only request such information if you cannot reproduce.
Arch Linux. Mate 1.12. amd64.

With the general attitude to bug reports here. I did not feel that you deserved much of my time.
I reported the issue to help you. The bug does not bother me.

**Comment by raveit65** [comment] 2015-12-11 23:57
> Did you even try it? Please only request such information if you cannot reproduce.
Arch Linux. Mate 1.12. amd64.

Yes, no problems in fedora :)
And NO, because my cristall ball is dead,
....... without basic informatitons nobody can reproduce it :)
> With the general attitude to bug reports here. I did not feel that you deserved much of my time.
I reported the issue to help you. The bug does not bother me.

Do you you really think being personal to me helps.
My motivation is six feed under after your reply

**Comment by maandree** [comment] 2015-12-12 00:03
Well, it is not always people try first.
Typo fix: Mate 1.12.1

I can reporduce it in a twm without any fancy started (except mate-settings-daemon and whatever that and mate-system-monitor may have started start.)

**Comment by monsta** [comment] 2016-01-08 12:16
I can't reproduce it... can you please provide a stacktrace via gdb?

**Comment by maandree** [comment] 2016-01-08 12:32
End of `strace` output:
```
access("/usr/lib/libgksu/gksu-run-helper", X_OK) = 0
getuid()                                = 1000
access("/usr/bin/xauth", X_OK)          = 0
getuid()                                = 1000
pipe2([14, 15], O_CLOEXEC)              = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f29a32d1b90) = 6265
close(15)                               = 0
fcntl(14, F_SETFD, 0)                   = 0
fstat(14, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f299400b000
read(14, "25b2bfe07d20d45384fd40c1e743d9e8"..., 4096) = 33
read(14, "", 4096)                      = 0
close(14)                               = 0
wait4(6265, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 6265
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=6265, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
munmap(0x7f299400b000, 4096)            = 0
uname({sysname="Linux", nodename="Zenith", ...}) = 0
poll([{fd=3, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=3, revents=POLLIN|POLLOUT}])
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\34\00097\4\0\300\2n\1\0\0\204\1\207\200\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 736
writev(3, [{"\1\30\n\0007\3 \3\312\4\0\0\234\377\234\377\1\0\1\0\0\0\0\0!\0\0\0\0\n\0\0"..., 356}], 1) = 356
open("/dev/ptmx", O_RDWR)               = 14
statfs("/dev/pts", {f_type="DEVPTS_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096}) = 0
ioctl(14, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(14, TIOCGPTN, [2])                = 0
stat("/dev/pts/2", {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 2), ...}) = 0
getuid()                                = 1000
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 15
connect(15, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(15)                               = 0
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 15
connect(15, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(15)                               = 0
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 15
fstat(15, {st_mode=S_IFREG|0644, st_size=1179, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f299400b000
read(15, "root:x:0:root\nbin:x:1:root,bin,d"..., 4096) = 1179
close(15)                               = 0
munmap(0x7f299400b000, 4096)            = 0
ioctl(14, TIOCSPTLCK, [0])              = 0
ioctl(14, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(14, TIOCGPTN, [2])                = 0
stat("/dev/pts/2", {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 2), ...}) = 0
open("/dev/pts/2", O_RDWR|O_NOCTTY)     = 15
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f29a32d1b90) = 6269
close(15)                               = 0
getuid()                                = 1000
open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 15
fstat(15, {st_mode=S_IFREG|0644, st_size=1817, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f299400b000
read(15, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 1817
close(15)                               = 0
munmap(0x7f299400b000, 4096)            = 0
read(14, "Password: ", 255)             = 10
ioctl(14, TCGETS, {B38400 opost isig icanon -echo ...}) = 0
sendmsg(13, {msg_name(0)=NULL, msg_iov(2)=[{"l\1\0\1,\0\0\0\f\0\0\0\211\0\0\0\1\1o\0\33\0\0\0/org/gno"..., 160}, {"\21\0\0\0/apps/gksu/prompt\0\0\0\v\0\0\0en_G"..., 44}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 204
poll([{fd=13, events=POLLIN}], 1, 25000) = 1 ([{fd=13, revents=POLLIN}])
recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"l\2\1\1L\0\0\0\247\26\0\0F\0\0\0\6\1s\0\t\0\0\0:1.11504"..., 2048}], msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 164
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
recvmsg(13, 0x7ffd02190a10, MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f299fdea428, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f299fdea428, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f299fdea428, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f299fdea428, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f299fdea428, FUTEX_WAKE_PRIVATE, 2147483647) = 0
sendmsg(13, {msg_name(0)=NULL, msg_iov(2)=[{"l\1\0\0014\0\0\0\r\0\0\0\211\0\0\0\1\1o\0\33\0\0\0/org/gno"..., 160}, {"\32\0\0\0/apps/gksu/save-to-keyring\0\0"..., 52}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 212
poll([{fd=13, events=POLLIN}], 1, 25000) = 1 ([{fd=13, revents=POLLIN}])
recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"l\2\1\1\\\0\0\0\250\26\0\0F\0\0\0\6\1s\0\t\0\0\0:1.11504"..., 2048}], msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 180
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
recvmsg(13, 0x7ffd02190590, MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
sendmsg(13, {msg_name(0)=NULL, msg_iov(2)=[{"l\1\0\0010\0\0\0\16\0\0\0\211\0\0\0\1\1o\0\33\0\0\0/org/gno"..., 160}, {"\27\0\0\0/apps/gksu/save-keyring\0\v\0\0\0"..., 48}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 208
poll([{fd=13, events=POLLIN}], 1, 25000) = 1 ([{fd=13, revents=POLLIN}])
recvmsg(13, {msg_name(0)=NULL, msg_iov(1)=[{"l\2\1\1`\0\0\0\251\26\0\0F\0\0\0\6\1s\0\t\0\0\0:1.11504"..., 2048}], msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 184
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
recvmsg(13, 0x7ffd02190590, MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
open("/home/mattias/.gksu.lock", O_RDONLY) = 15
fcntl(15, F_GETLK, {type=F_UNLCK, whence=SEEK_SET, start=0, len=0, pid=18446744072150466480}) = 0
close(15)                               = 0
open("/home/mattias/.gksu.lock", O_RDWR|O_CREAT|O_TRUNC, 0640) = 15
fcntl(15, F_SETFD, FD_CLOEXEC)          = 0
fcntl(15, F_SETLK, {type=F_WRLCK, whence=SEEK_SET, start=0, len=0}) = 0
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\241\10;77\3 \3\353\1\0\0new: ID=mate-system-"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 256
recvmsg(3, 0x7ffd02190a00, 0)           = -1 EAGAIN (Resource temporarily unavailable)
mmap(NULL, 5763072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f298d2ad000
poll([{fd=3, events=POLLIN|POLLOUT}], 1, 4294967295) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{"\1\30\16\0006\3 \3\312\4\0\0\0\0\0\0@\6\260\4\0\0\1\0!\0\0\0\32*\0\0"..., 76}, {NULL, 0}, {"", 0}], 3) = 76
poll([{fd=3, events=POLLIN}], 1, 4294967295) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\0\10C7\3\0 \3\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
poll([{fd=3, events=POLLIN}], 1, 4294967295) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\1\1E7\0\0\0\0\2\0\240\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
open("/usr/share/X11/XErrorDB", O_RDONLY) = 16
fstat(16, {st_mode=S_IFREG|0644, st_size=42077, ...}) = 0
read(16, "!\n! Copyright 1993, 1995, 1998  "..., 42077) = 42077
close(16)                               = 0
write(2, "The program 'mate-system-monitor"..., 579The program 'mate-system-monitor' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 14147 error_code 8 request_code 1 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
) = 579
exit_group(1)                           = ?
+++ exited with 1 +++
```

`valgrind` (without any switches) output is surprisingly clean; nothing of interest.

No information can be extracted using `gdb`.

**Comment by monsta** [comment] 2016-01-12 10:57
Well, this output isn't very helpful...

Try this:
```
GDK_SYNCHRONIZE=1 gdb mate-system-monitor
```

**Comment by maandree** [comment] 2016-01-12 11:01
Nothing helpful there either.
I will see if I can compile it and figure out what is wrong,
but in my experience, compiling MATE is very difficult.

**Comment by monsta** [comment] 2016-01-12 11:06
Did you install debug info package for mate-system-monitor?

**Comment by maandree** [comment] 2016-01-12 11:19
I have the GTK2 version packaged for Arch Linux, there are not other packages available except for the GTK3. My guess is that it is no debug info in the package.

**Comment by monsta** [comment] 2016-01-12 11:31
@flexiondotorg: is there a debug info package for m-s-m in Arch?

**Comment by maandree** [comment] 2016-01-12 11:38
This version of this package compiled without a problem.

**Comment by maandree** [comment] 2016-01-12 12:20
The failing function call is `gksu_run(command, &e);` in `procman_gksu_create_root_password_dialog`.

**Comment by monsta** [comment] 2016-01-16 12:15
Interesting... but as you can see in the [source file](https://github.com/mate-desktop/mate-system-monitor/blob/master/src/procman_gksu.cpp), this function is simply loaded from ```libgksu2.so```. So, basically, we can't fix the problem at our side...

Were there any recent updates to libgksu in Arch?

**Comment by maandree** [comment] 2016-01-16 12:46
The latest version of libgksu on Arch is version 2.0.12, release 2015-May-17.

**Comment by monsta** [comment] 2016-01-17 11:12
Ok, I found a patch that just might fix it...

Can you please ask libgksu maintainers to try [this patch](https://launchpadlibrarian.net/36875787/libgksu-rgba-fix.diff)? Or try it yourself if you can.

The patch has been attached to [this bug report](https://bugs.launchpad.net/bugs/491521). Notice a heap of "X Window System error" crashes mentioned there - it hints it might be the same problem as the one you have.

**Comment by maandree** [comment] 2016-01-17 14:30
The passphrase dialogue now shows up, but after entering my passphrase and waiting a few seconds
I get a dialogue with out error message
```
Cannot kill process with PID 28330 with signal 9.
Input/output error
```

**Comment by monsta** [comment] 2016-01-28 12:13
Weird...
Can you also try renicing a root process for a test? It should also display gksu dialog.

**Comment by maandree** [comment] 2016-01-31 20:26
No luck. Same behaviour, but with the error messaeg

```
Cannot change the priority of process with PID 3514 to -5.
Input/output error
```

**Comment by monsta** [comment] 2016-02-01 18:42
Well, I guess you'll have to ask libgksu maintainers about this...

In the meanwhile, I plan to replace gksu with pkexec for 1.14. GTK+3 build of m-s-m will be the default one in this version, and it doesn't work with libgksu due to it being GTK+2 only. :confused:

**Comment by monsta** [comment] 2016-03-30 19:24
Well, pkexec support will be added later (for 1.16 release). For now, libgksu loading had been replaced with running gksu binary. It should fix this problem.

**Comment by monsta** [comment] 2016-04-09 09:21
1.14 is released with the fix.

**Closed by monsta** 2016-04-09 09:21 UTC
