### ISSUE TITLE
mate-system-monitor crash on openindiana

### ISSUE THREAD

**Issue by etty82** [mate-desktop/mate-system-monitor#118] opened 2018-04-27 17:26 UTC
mate-system-monitor crashes when switching to Processes tab.
Here the output from mate-terminal after switching to processes tab:
(...)
(mate-system-monitor:2137): Gtk-CRITICAL **: gtk_tree_view_row_expanded: assertion 'path != NULL' failed
(mate-system-monitor:2137): Gtk-CRITICAL **: gtk_tree_view_expand_row: assertion 'path != NULL' failed
(mate-system-monitor:2137): Gtk-CRITICAL **: gtk_tree_store_set_valist: assertion 'VALID_ITER (iter, tree_store)' failed
(mate-system-monitor:2137): Gtk-CRITICAL **: gtk_tree_store_set_valist: assertion 'VALID_ITER (iter, tree_store)' failed
(mate-system-monitor:2137): Gtk-CRITICAL **: gtk_tree_store_get_value: assertion 'VALID_ITER (iter, tree_store)' failed
(mate-system-monitor:2137): GLib-GObject-WARNING **: gtype.c:4265: type id '0' is invalid
(mate-system-monitor:2137): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced
Segmentation Fault (core dump created)

Mate version: Mate Desktop Enviroment 1.18.0
Package version: mate-system-monitor 1.18.2
Distro: Openindiana Hipster 2017.10 (illumos-cb76bcef7c)

**Comment by lukefromdc** [comment] 2018-04-27 19:31
I am guessing this is distro-specific as I've never encountered this on Debian Unstable and use the process tab all the time.  OK, you are using MATE 1.18, what GTK 3 and glib version do you have?

**Comment by etty82** [comment] 2018-04-27 22:34
I have:
gtk3 -> 3.18.9-2018.0.0.3
glib -> 2.54.3-2018.0.0.0

**Comment by lukefromdc** [comment] 2018-04-27 22:36
@raveit65 , @monsta , other dev: can anyone here duplicate this crash? I can't work on it because I can't duplicate it

**Comment by raveit65** [comment] 2018-04-27 22:50
No, i can't reproduce it either and i don't have any report about a related problem at red hat bugzilla.

**Comment by lukefromdc** [comment] 2018-04-27 22:51
The error text looks like the treeview is either being interacted with before it can open, after it has been destroyed, or has not been found at all. Could be a packaging issue or a race condition like crashes I got and others did not in Caja (some of the time, on clicking desktop mounts) that turned out to be an attempt to access a widget (the pathbar) before it could be set up. Applying a bunch of GNOME commits that removed the offending code fixed that one.

If you can install the debugging symbols and run mate-system-monitor under gdb, then post the backtrace that might point to the offending line of code. If later GNOME commits to gnome-system-monitor removed that (as in that Caja crash and fix), that might offer a solution but someone experiencing the crash would need to test.

Here's how to use gdb:

1: make sure the debugging symbols are installed, as they would be if you installed a local build with make install or installed a package of the debugging symbols for mate-system-monitor.

2: Make sure you have gdb installed, you probably already do.

3: type
`gdb mate-system-monitor`

4: type "run" to open mate-system-monitor, open the processes tab and let it crash. You will have text in terminal similar to buy maybe more detailed than running it directly. Cut and paste that to a text file. That's not your backtrace but can be useful along with it.

4: Get the backtrace: type
thread apply all bt full``
in the same terminal you have gdb running it, and you will get a bunch of text. pagedown to the bottom of it, then cut and paste all of it from the start to another text file. Post both of those here, what we are looking for is line number or function names from the source code where the crash occurs.

**Comment by monsta** [comment] 2018-04-28 08:26
I can't reproduce this, at least with git master.
All I can see is that warnings happen in `insert_info_to_tree` function, when "Dependencies" is enabled (press Ctrl-D).

```C++
    if (procdata->config.show_tree) {

        ProcInfo *parent = 0;

        if (not forced)
            parent = ProcInfo::find(info->ppid);

        if (parent) {
            GtkTreePath *parent_node = gtk_tree_model_get_path(model, &parent->node);
            gtk_tree_store_insert(GTK_TREE_STORE(model), &info->node, &parent->node, 0);

            if (!gtk_tree_view_row_expanded(GTK_TREE_VIEW(procdata->tree), parent_node)
#ifdef __linux__
                // on linuxes we don't want to expand kthreadd by default (always has pid 2)
                && (parent->pid != 2)
#endif
            )
                gtk_tree_view_expand_row(GTK_TREE_VIEW(procdata->tree), parent_node, FALSE);
            gtk_tree_path_free(parent_node);
        } else
            gtk_tree_store_insert(GTK_TREE_STORE(model), &info->node, NULL, 0);
    }
    else
        gtk_tree_store_insert (GTK_TREE_STORE (model), &info->node, NULL, 0);

    gtk_tree_store_set (GTK_TREE_STORE (model), &info->node,
                        COL_POINTER, info,
                        COL_NAME, info->name,
                        COL_ARGS, info->arguments,
                        COL_TOOLTIP, info->tooltip,
                        COL_PID, info->pid,
                        COL_SECURITYCONTEXT, info->security_context,
                        -1);
```

First two warnings are caused by `parent_node` pointer being `NULL`.

**Comment by monsta** [comment] 2018-04-28 08:34
Just tried 1.18.2 in a VM with GTK+ 3.18 - not reproducible there as well.

**Comment by etty82** [comment] 2018-04-28 09:05
[thread_gdb.txt](https://github.com/mate-desktop/mate-system-monitor/files/1957511/thread_gdb.txt)
[gdb.txt](https://github.com/mate-desktop/mate-system-monitor/files/1957512/gdb.txt)

I built from source mate-system-monitor and here the two files with the output from gdb.
Thanks a lot!

**Comment by monsta** [comment] 2018-04-28 10:52
Thanks.
I think you can get the app back to life by setting tree-like display of processes to false:

```
$ gsettings set org.mate.system-monitor show-tree false
```
Then you can switch to process tab again. Check the ID column there: do you have a process with ID 0 in the list?

**Comment by etty82** [comment] 2018-04-28 20:46
It works! :)
Thank you so much.
Yes, I have an ID 0 process of root user with the status "stopped", and process name "sched".

**Comment by etty82** [comment] 2018-04-28 20:50
In the terminal for each process I get like this:
glibtop: pread (/proc/2183/xmap): Value too large for defined data type
... but it works!

**Comment by monsta** [comment] 2018-04-29 13:00
Ok, looks like we have https://bugzilla.gnome.org/742070 here, only with Solaris-like system instead of BSD. Wonder why no BSD users reported that... we surely have some MATE users there.

I'll pick some relevant commits from gnome-system-monitor.

**Comment by etty82** [comment] 2018-04-29 21:34
I see... thanks a lot!

**Comment by pyhalov** [comment] 2018-05-04 13:31
I've merged https://github.com/GNOME/gnome-system-monitor/commit/65c8b3309f239ba4404212d988d380856bf226c9 , https://github.com/GNOME/gnome-system-monitor/commit/77a81402480fd8aedd468246061bee332c3ddac0 , https://github.com/GNOME/gnome-system-monitor/commit/451579613b70d7f4bfd4614e3d7bfbc67b2a439b to mate-system-monitor, tested on 1.18 branch, this seems to fix the crash. 
See https://github.com/mate-desktop/mate-system-monitor/pull/119

**Comment by etty82** [comment] 2018-05-04 14:40
Yes, it fixes the crash without setting
`$ gsettings set org.mate.system-monitor show-tree false`

Thanks!

**Closed** 2018-05-07 19:15 UTC
