### ISSUE TITLE
Gtk+-3: Can not resize process columns larger than a certiain size

### ISSUE THREAD

**Issue by infirit** [mate-desktop/mate-system-monitor#41] opened 2014-10-29 14:59 UTC
I can make a column smaller but when I tried to resize larger it only allows up to a certain width.

**Comment by monsta** [comment] 2015-11-02 12:04
Looks like it was an issue in GTK+3 itself as I can't reproduce it with GTK+ 3.18.2.
@raveit65: can you reproduce it?

**Comment by raveit65** [comment] 2015-11-02 19:00
Nope, works here with gtk+-3.16. ........i quess report was with 3.14.
But if i reduce the first colum size to zero in disk usage tap, the window closed :dancers:

**Comment by monsta** [comment] 2015-11-02 19:02
Wow :smile:
But that's for another report I think, the current one is about process tab.

**Comment by monsta** [comment] 2015-11-24 10:25
@clefebvre: damn... it's reproducible in Mint 17.3. Reported in [this comment](http://blog.linuxmint.com/?p=2937#comment-121118):

> only shows the icon of the process name instead of the letters unless the window for the System Monitor is fully maximized

It's indeed like that, columns can't be properly resized, so only process icon is visible unless you maximize the window. I can reproduce it as well.

In Betsy it seems to be alright, so must be indeed an issue in older GTK+3.

**Comment by monsta** [comment] 2015-12-11 12:55
Closing as it's not fixable at our level.

**Closed by monsta** 2015-12-11 12:55 UTC
Labels: confirmed
